### ISSUE TITLE
[Request] Nuget Publish

### ISSUE THREAD

**Issue by CliffCawley** [enjin/enjin-csharp-sdk#35]
Can you publish to nuget? This gives us an easy way to update to the latest when new updates are released :)

https://docs.microsoft.com/en-us/nuget/nuget-org/publish-a-package

**Comment by Favorlock** [comment]
We've been looking into this and will publish to Nuget eventually. With the SDK in alpha we're a bit hesitant to publish since there may be many breaking changes.

**Comment by seertenedos** [comment]
You can publish it as a pre-release so people know it is not final. It really would be much better if there was a NuGet published

**Comment by BishopJohnson** [comment]
My apologies for the long wait on this issue. The C# SDK is now available on NuGet at the follow: https://www.nuget.org/packages/Enjin.Sdk.CSharp.

**Comment by seertenedos** [comment]
thanks i can confirm the nuget is working perfectly
