### ISSUE TITLE
Query is not being compiled in CreateRequestBody method

### ISSUE THREAD

**Issue by JPLanh** [enjin/enjin-csharp-sdk#53]
I'm currently trying this out in unity and I notice that the query variable within the CreateRequestBody method that's located in the BaseSchema.cs file is not compiling the query, but the variables variable is generating the input properly.

On a side note: Base on what I have gathered so far, I wouldn't be able to really do anything anyways assuming that most of the current GraphQL are for the early access api correct (i.e. AuthProject is an early access GraphQL query)?

**Comment by BishopJohnson** [comment]
Hi @JPLanh,

Unfortunately the C# SDK cannot be ported into Unity as is without making necessary modifications to address technical issues, such as the one you're seeing with the GraphQL queries not being compiled. There is a dedicated Unity SDK on the [Unity Asset Store](https://assetstore.unity.com/packages/tools/utilities/blockchain-sdk-by-enjin-124133) for the current platform API.

Also your assessment is correct. Currently the C# SDK is designed for an early access API. Our support team is available at support@enjin.io for any questions or assistance.
