### ISSUE TITLE
Syntax Error: Unexpected <EOF> when trying to get access token 

### ISSUE THREAD

**Issue by MeltdownInteractive** [enjin/enjin-csharp-sdk#61]
I added my project on Jumpnet. UUID : 7577d864-9b88-443c-8897-8d3e941dfb9c

I can use the GraphQL Playground just fine to make a call to https://jumpnet.cloud.enjin.io/graphql/project, 
passing in the UUID and secret, and getting back the access token.  

But when I do the same using the C# SDK, I get the following error...
**Syntax Error: Unexpected <EOF>**

```
ProjectClient client = new ProjectClient(EnjinHosts.JUMP_NET);
            
            AuthProject project = new AuthProject()
                .Uuid("7577d864-9b88-443c-8897-8d3e941dfb9c")
                .Secret("xxxxx");

            GraphqlResponse<AccessToken> res = client.AuthProject(project).Result;
```

Any ideas?

**Comment by MeltdownInteractive** [comment]
@BishopJohnson Unfortunately there is no more information I can provide. When I debug the result object, this is all I can see in Rider...

![debug](https://user-images.githubusercontent.com/981794/156458455-cc965af7-c023-42ff-91db-d31341cb661a.jpg)

With the only error information being a 400 response and message of 

`Syntax Error: Unexpected <EOF>`

**Comment by BishopJohnson** [comment]
At the moment I'm not entirely sure what is causing this issue, but I have a some ideas as to what it could be.

For .NET, the most common reports I've seen of an <EOF> syntax error when making an HTTP request has to do with an unsupported security protocol. If possible, I would recommend updating your .NET version and seeing if that fixes the issue. The SDK itself is built on .NET Standard 2.0 which allows it to work with all modern platforms.

If that does not resolve the issue then some things I'd be interested in knowing are:

- If you were able to use the query in the past successfully through the SDK and it has only recently become an issue?
- If you have only used JumpNet for development or if you have tried testing your project through either the [Kovan](https://kovan.cloud.enjin.io/login) or [Goerli](https://goerli.cloud.enjin.io/login) test networks.
- What version of the SDK are you using and if you're using the NuGet package?
- What kind of application you're trying to make? Is it a standalone .NET project or a Unity project?

**Comment by MeltdownInteractive** [comment]
@BishopJohnson I ended up doing a bit of a clean up. Initially I didn't use the NUGET package, and just downloaded the SDK manually and tried to get that working and adding dependencies manually etc. 

I started again with the NUGET package and everything seems to work now. Apologies.
